/**
 * Demo professionals — seeded marketplace supply for the demo backend and
 * Firestore seeding. Photos use stable Unsplash URLs; UI falls back to
 * initials when an image fails to load.
 */
import type { Availability, DayWindow, ProfessionalProfile } from '../../models/types';
import { SUBCITIES } from '../../constants/geo';

function subcityGeo(id: string) {
  const s = SUBCITIES.find((x) => x.id === id) ?? SUBCITIES[0]!;
  if (!s) throw new Error('no subcity');
  return { subcity: s.name, city: 'Addis Ababa', geo: s.geo };
}

function hours(days: number[], start = '08:00', end = '18:00'): Record<number, DayWindow> {
  const wh: Record<number, DayWindow> = {};
  for (let d = 0; d <= 6; d++) wh[d] = { enabled: days.includes(d), start, end };
  return wh;
}

function availability(days: number[], start?: string, end?: string): Availability {
  return { workingHours: hours(days, start, end), vacationDates: [], slotDurationMin: 120, bufferMin: 30 };
}

const U = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=400&q=70`;

export const DEMO_PROFESSIONALS: ProfessionalProfile[] = [
  {
    uid: 'pro-marta',
    displayName: 'Marta Bekele',
    businessName: 'Marta Sparkle Cleaning',
        about:
      'Professional home cleaning with a 4-person trusted team. We bring our own eco-friendly supplies and cover most of eastern Addis. 6 years of experience with apartments, villas and offices.',
    categoryIds: ['cleaning', 'laundry'],
    serviceIds: ['house-cleaning', 'deep-cleaning', 'move-out-cleaning', 'office-cleaning', 'laundry-wash', 'dry-cleaning', 'ironing'],
    services: [
      { id: 's1', name: 'Standard home cleaning', price: 700, unit: 'visit' },
      { id: 's2', name: 'Deep cleaning (up to 3BR)', price: 1600, unit: 'visit' },
      { id: 's3', name: 'Move-out cleaning', price: 1800, unit: 'visit' },
      { id: 's4', name: 'Office cleaning', price: 2200, unit: 'visit' },
      { id: 's5', name: 'Wash & fold (per bag)', price: 350, unit: 'bag' },
      { id: 's6', name: 'Dry cleaning (5 items)', price: 600, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Kirkos', 'Nifas Silk'],
    baseLocation: subcityGeo('bole'),
    startingPrice: 700,
    priceUnit: 'visit',
    rating: 4.9,
    reviewCount: 187,
    jobsCompleted: 412,
    yearsExperience: 6,
    responseRatePct: 97,
    medianResponseMinutes: 8,
    completionRatePct: 99,
    verified: true,
    badges: ['Top Rated', 'Background Checked', 'Eco Supplies'],
    availability: availability([1, 2, 3, 4, 5, 6]),
    portfolio: [
      { id: 'p1', title: 'Deep clean — Bole apartment', imageURL: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=70' },
      { id: 'p2', title: 'Villa post-construction', imageURL: 'https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=600&q=70' },
      { id: 'p3', title: 'Office — Kazanchis', imageURL: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [
      { id: 'c1', name: 'Business license', type: 'license', verified: true },
      { id: 'c2', name: 'Team ID verified', type: 'id', verified: true },
    ],
    joinedAt: Date.now() - 190 * 86400000,
    online: true,
  },
  {
    uid: 'pro-abebe',
    displayName: 'Abebe Kebede',
    businessName: 'Abebe Plumbing Works',
        about:
      'Licensed plumber for 12 years. Leak detection, pipe repair, water heaters and emergencies. Same-day service in central Addis. I answer fast — usually within 10 minutes.',
    categoryIds: ['plumbing'],
    serviceIds: ['plumbing-general', 'drain-cleaning', 'faucet-leak', 'water-heater', 'emergency-plumbing'],
    services: [
      { id: 's1', name: 'Visit & diagnosis', price: 400, unit: 'visit' },
      { id: 's2', name: 'Leak repair (from)', price: 600, unit: 'visit' },
      { id: 's3', name: 'Drain unblocking', price: 800, unit: 'visit' },
      { id: 's4', name: 'Water heater service', price: 900, unit: 'visit' },
      { id: 's5', name: 'Emergency call-out', price: 1200, unit: 'visit' },
    ],
    serviceArea: ['Bole', 'Kirkos', 'Arada', 'Lideta', 'Yeka'],
    baseLocation: subcityGeo('kirkos'),
    startingPrice: 400,
    priceUnit: 'visit',
    rating: 4.8,
    reviewCount: 254,
    jobsCompleted: 731,
    yearsExperience: 12,
    responseRatePct: 95,
    medianResponseMinutes: 10,
    completionRatePct: 98,
    verified: true,
    badges: ['Top Rated', 'Licensed', '24/7 Emergency'],
    availability: availability([0, 1, 2, 3, 4, 5, 6], '07:00', '20:00'),
    portfolio: [
      { id: 'p1', title: 'Bathroom re-pipe — Piassa', imageURL: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=600&q=70' },
      { id: 'p2', title: 'Water heater install', imageURL: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [
      { id: 'c1', name: 'Plumbing license (Grade 2)', type: 'license', verified: true },
    ],
    joinedAt: Date.now() - 400 * 86400000,
    online: true,
  },
  {
    uid: 'pro-selam',
    displayName: 'Selam Tadesse',
    businessName: 'SelamShoot Photography',
        about:
      'Wedding and event photographer with a candid, documentary style. 200+ weddings covered across Ethiopia. Packages include editing, online gallery and prints.',
    categoryIds: ['events'],
    serviceIds: ['photography', 'event-planning'],
    services: [
      { id: 's1', name: 'Event photography (4 hrs)', price: 4500, unit: 'flat' },
      { id: 's2', name: 'Full wedding day', price: 15000, unit: 'flat' },
      { id: 's3', name: 'Portrait session', price: 1800, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Arada', 'Kirkos', 'Gullele', 'Akaki'],
    baseLocation: subcityGeo('yeka'),
    startingPrice: 1800,
    priceUnit: 'flat',
    rating: 5.0,
    reviewCount: 96,
    jobsCompleted: 210,
    yearsExperience: 8,
    responseRatePct: 92,
    medianResponseMinutes: 25,
    completionRatePct: 100,
    verified: true,
    badges: ['Top Rated', 'Drone Certified'],
    availability: availability([1, 2, 3, 4, 5, 6], '09:00', '19:00'),
    portfolio: [
      { id: 'p1', title: 'Wedding — Bishoftu', imageURL: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=70' },
      { id: 'p2', title: 'Graduation, AAU', imageURL: 'https://images.unsplash.com/photo-1522077721107-6a03840f2c1c?auto=format&fit=crop&w=600&q=70' },
      { id: 'p3', title: 'Studio portraits', imageURL: 'https://images.unsplash.com/photo-1519638399535-1b036603ac77?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [{ id: 'c1', name: 'Drone pilot certification', type: 'certification', verified: true }],
    joinedAt: Date.now() - 300 * 86400000,
  },
  {
    uid: 'pro-dawit',
    displayName: 'Dawit Alemu',
    businessName: 'Dawit Electric',
        about:
      'Certified electrician. Panel upgrades, wiring for new buildings, fault finding and smart-home lighting. Safety-first — every job ends with a full check.',
    categoryIds: ['electrical'],
    serviceIds: ['electrical-repair', 'lighting', 'wiring', 'panel-upgrade'],
    services: [
      { id: 's1', name: 'Diagnosis visit', price: 400, unit: 'visit' },
      { id: 's2', name: 'Fixture install (per unit)', price: 250, unit: 'visit' },
      { id: 's3', name: 'Room wiring', price: 1800, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Addis Ketema', 'Arada', 'Kolfe'],
    baseLocation: subcityGeo('yeka'),
    startingPrice: 250,
    priceUnit: 'visit',
    rating: 4.7,
    reviewCount: 141,
    jobsCompleted: 380,
    yearsExperience: 9,
    responseRatePct: 90,
    medianResponseMinutes: 18,
    completionRatePct: 97,
    verified: true,
    badges: ['Licensed', 'Background Checked'],
    availability: availability([1, 2, 3, 4, 5], '08:30', '18:30'),
    portfolio: [
      { id: 'p1', title: 'Panel upgrade — CMC', imageURL: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [{ id: 'c1', name: 'Electrical license (Grade 3)', type: 'license', verified: true }],
    joinedAt: Date.now() - 250 * 86400000,
    online: true,
  },
  {
    uid: 'pro-hanna',
    displayName: 'Hanna Girma',
    businessName: 'Hanna Glow Beauty',
        about:
      'Mobile makeup artist & nail technician. Wedding packages, event glam and home manicure/pedicure. I come to you anywhere in Addis with a full kit.',
    categoryIds: ['beauty'],
    serviceIds: ['makeup-nails', 'hair-barber', 'massage'],
    services: [
      { id: 's1', name: 'Event makeup', price: 1200, unit: 'visit' },
      { id: 's2', name: 'Bridal package', price: 3500, unit: 'flat' },
      { id: 's3', name: 'Mani + pedi', price: 600, unit: 'visit' },
    ],
    serviceArea: ['Bole', 'Kirkos', 'Yeka', 'Nifas Silk', 'Arada'],
    baseLocation: subcityGeo('nifas-silk'),
    startingPrice: 600,
    priceUnit: 'visit',
    rating: 4.9,
    reviewCount: 78,
    jobsCompleted: 190,
    yearsExperience: 5,
    responseRatePct: 96,
    medianResponseMinutes: 12,
    completionRatePct: 99,
    verified: true,
    badges: ['Rising Star', 'Home Visit'],
    availability: availability([1, 2, 3, 4, 5, 6], '09:00', '20:00'),
    portfolio: [
      { id: 'p1', title: 'Bridal glam', imageURL: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [],
    joinedAt: Date.now() - 120 * 86400000,
    online: true,
  },
  {
    uid: 'pro-yonas',
    displayName: 'Yonas Haile',
    businessName: 'Yonas Movers',
        about:
      'Moving crew with 3.5-ton truck. Packing, loading, transport and setup at your new place. Careful with furniture and electronics — blankets and wraps included.',
    categoryIds: ['moving'],
    serviceIds: ['moving-help', 'packing', 'delivery'],
    services: [
      { id: 's1', name: 'Studio/1BR move (in-city)', price: 2500, unit: 'flat' },
      { id: 's2', name: '2–3BR move (in-city)', price: 4500, unit: 'flat' },
      { id: 's3', name: 'Packing service', price: 900, unit: 'visit' },
      { id: 's4', name: 'Item courier', price: 200, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Kirkos', 'Yeka', 'Lideta', 'Kolfe', 'Akaki', 'Arada', 'Gullele', 'Addis Ketema', 'Nifas Silk'],
    baseLocation: subcityGeo('kirkos'),
    startingPrice: 200,
    priceUnit: 'flat',
    rating: 4.6,
    reviewCount: 203,
    jobsCompleted: 560,
    yearsExperience: 7,
    responseRatePct: 88,
    medianResponseMinutes: 30,
    completionRatePct: 96,
    verified: true,
    badges: ['Insured', 'Truck Included'],
    availability: availability([1, 2, 3, 4, 5, 6], '07:00', '19:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Vehicle insurance', type: 'insurance', verified: true }],
    joinedAt: Date.now() - 350 * 86400000,
  },
  {
    uid: 'pro-tigist',
    displayName: 'Tigist Wolde',
    businessName: 'Tigist Home Care',
        about:
      'Solo cleaner for recurring home care. Regular weekly and bi-weekly clients get priority scheduling and discounted rates. Trustworthy with references.',
    categoryIds: ['cleaning'],
    serviceIds: ['house-cleaning', 'deep-cleaning'],
    services: [
      { id: 's1', name: 'Recurring clean (weekly)', price: 550, unit: 'visit' },
      { id: 's2', name: 'One-time deep clean', price: 1400, unit: 'visit' },
    ],
    serviceArea: ['Arada', 'Gullele', 'Yeka', 'Addis Ketema'],
    baseLocation: subcityGeo('arada'),
    startingPrice: 550,
    priceUnit: 'visit',
    rating: 4.8,
    reviewCount: 64,
    jobsCompleted: 121,
    yearsExperience: 4,
    responseRatePct: 93,
    medianResponseMinutes: 20,
    completionRatePct: 98,
    verified: true,
    badges: ['Rising Star'],
    availability: availability([1, 2, 3, 4, 5, 6], '08:00', '17:00'),
    portfolio: [],
    credentials: [],
    joinedAt: Date.now() - 90 * 86400000,
  },
  {
    uid: 'pro-mulugeta',
    displayName: 'Mulugeta Assefa',
    businessName: 'Mulugeta Carpentry',
        about:
      'Carpenter and furniture maker. Custom wardrobes, kitchen cabinets, door repair and furniture restoration. Workshop in Kolfe with delivery.',
    categoryIds: ['home-repair'],
    serviceIds: ['furniture-assembly', 'carpentry'],
    services: [
      { id: 's1', name: 'Furniture assembly visit', price: 350, unit: 'visit' },
      { id: 's2', name: 'Custom wardrobe (per m)', price: 4500, unit: 'flat' },
      { id: 's3', name: 'Door repair', price: 500, unit: 'visit' },
    ],
    serviceArea: ['Kolfe', 'Nifas Silk', 'Addis Ketema', 'Lideta', 'Gullele'],
    baseLocation: subcityGeo('kolfe'),
    startingPrice: 350,
    priceUnit: 'visit',
    rating: 4.7,
    reviewCount: 112,
    jobsCompleted: 240,
    yearsExperience: 15,
    responseRatePct: 85,
    medianResponseMinutes: 45,
    completionRatePct: 95,
    verified: false,
    badges: [],
    availability: availability([1, 2, 3, 4, 5], '08:00', '18:00'),
    portfolio: [
      { id: 'p1', title: 'Kitchen cabinets', imageURL: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [],
    joinedAt: Date.now() - 500 * 86400000,
  },
  {
    uid: 'pro-biniyam',
    displayName: 'Biniyam Tesfaye',
    businessName: 'Biniyam Tech Fix',
        about:
      'Computer and phone repair technician. Screen replacement, virus removal, data recovery, office WiFi setup. Pickup and delivery available.',
    categoryIds: ['tech'],
    serviceIds: ['computer-repair', 'phone-repair', 'it-network'],
    services: [
      { id: 's1', name: 'Diagnosis', price: 300, unit: 'visit' },
      { id: 's2', name: 'Phone screen (from)', price: 1800, unit: 'flat' },
      { id: 's3', name: 'WiFi setup visit', price: 700, unit: 'visit' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Kirkos', 'Arada'],
    baseLocation: subcityGeo('bole'),
    startingPrice: 300,
    priceUnit: 'visit',
    rating: 4.6,
    reviewCount: 87,
    jobsCompleted: 260,
    yearsExperience: 6,
    responseRatePct: 98,
    medianResponseMinutes: 6,
    completionRatePct: 97,
    verified: true,
    badges: ['Fast Responder', 'Warranty: 90 days'],
    availability: availability([1, 2, 3, 4, 5, 6], '09:00', '21:00'),
    portfolio: [],
    credentials: [],
    joinedAt: Date.now() - 200 * 86400000,
    online: true,
  },
  {
    uid: 'pro-kalkidan',
    displayName: 'Kalkidan Mekonnen',
    businessName: 'Kalkidan Tutoring',
        about:
      'Maths and physics tutor for Grade 6–12 and first-year university. National exam specialist (Grade 8 & 12). Home visits in Yeka/Bole or online.',
    categoryIds: ['lessons'],
    serviceIds: ['tutoring', 'language-lessons'],
    services: [
      { id: 's1', name: 'Home tutoring (per hr)', price: 250, unit: 'hour' },
      { id: 's2', name: 'Online session (per hr)', price: 180, unit: 'hour' },
      { id: 's3', name: 'Exam-prep package (10 sessions)', price: 2200, unit: 'flat' },
    ],
    serviceArea: ['Yeka', 'Bole', 'Kirkos'],
    baseLocation: subcityGeo('yeka'),
    startingPrice: 180,
    priceUnit: 'hour',
    rating: 4.9,
    reviewCount: 59,
    jobsCompleted: 88,
    yearsExperience: 5,
    responseRatePct: 94,
    medianResponseMinutes: 15,
    completionRatePct: 100,
    verified: true,
    badges: ['Exam Specialist'],
    availability: availability([1, 2, 3, 4, 5, 6], '14:00', '20:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'BSc Mathematics, AAU', type: 'certification', verified: true }],
    joinedAt: Date.now() - 150 * 86400000,
    online: true,
  },
  {
    uid: 'pro-getachew',
    displayName: 'Getachew Feleke',
    businessName: 'Getachew HVAC & Appliance',
        about:
      'AC installation, gas refill and appliance repair (fridges, washers, stoves). 11 years in the trade with original spare-parts sourcing.',
    categoryIds: ['home-repair'],
    serviceIds: ['appliance-repair', 'hvac', 'electrical-repair'],
    services: [
      { id: 's1', name: 'AC service & gas refill', price: 1200, unit: 'visit' },
      { id: 's2', name: 'Appliance diagnosis', price: 400, unit: 'visit' },
      { id: 's3', name: 'AC install (per unit)', price: 2000, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Nifas Silk', 'Akaki', 'Kirkos'],
    baseLocation: subcityGeo('akaki'),
    startingPrice: 400,
    priceUnit: 'visit',
    rating: 4.5,
    reviewCount: 73,
    jobsCompleted: 175,
    yearsExperience: 11,
    responseRatePct: 82,
    medianResponseMinutes: 50,
    completionRatePct: 94,
    verified: true,
    badges: ['Spare Parts Sourcing'],
    availability: availability([1, 2, 3, 4, 5, 6], '08:00', '18:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Refrigeration certificate', type: 'certification', verified: true }],
    joinedAt: Date.now() - 600 * 86400000,
  },
  {
    uid: 'pro-rediet',
    displayName: 'Rediet Solomon',
    businessName: 'Rediet Events & Catering',
        about:
      'Full-service event planning: weddings, graduations and corporate events. In-house catering (traditional & international), tents, decor and coordination.',
    categoryIds: ['events'],
    serviceIds: ['event-planning', 'catering', 'tents-rentals'],
    services: [
      { id: 's1', name: 'Event coordination', price: 6000, unit: 'flat' },
      { id: 's2', name: 'Catering (per guest)', price: 350, unit: 'flat' },
      { id: 's3', name: 'Tent & chair rental (100 guests)', price: 9000, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Arada', 'Kirkos', 'Gullele', 'Akaki', 'Kolfe', 'Lideta', 'Addis Ketema', 'Nifas Silk'],
    baseLocation: subcityGeo('bole'),
    startingPrice: 350,
    priceUnit: 'flat',
    rating: 4.8,
    reviewCount: 44,
    jobsCompleted: 96,
    yearsExperience: 7,
    responseRatePct: 90,
    medianResponseMinutes: 35,
    completionRatePct: 98,
    verified: true,
    badges: ['Full Package'],
    availability: availability([1, 2, 3, 4, 5, 6], '09:00', '18:00'),
    portfolio: [
      { id: 'p1', title: 'Wedding for 300 — Sheraton gardens', imageURL: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [{ id: 'c1', name: 'Food handling certificate', type: 'certification', verified: true }],
    joinedAt: Date.now() - 280 * 86400000,
  },

  /* ── Ethiopia expansion pros ── */
  {
    uid: 'pro-kebede',
    displayName: 'Kebede Wolde',
    businessName: 'KK Auto Care',
        about: 'Mobile mechanic with 14 years on Toyota, Suzuki and Nissan. I come to your home or office with a full toolset — diagnosis, brakes, batteries and routine service without towing your car across town.',
    categoryIds: ['auto'],
    serviceIds: ['auto-mechanic', 'auto-battery', 'auto-detailing', 'roadside'],
    services: [
      { id: 's1', name: 'Diagnosis visit', price: 700, unit: 'visit' },
      { id: 's2', name: 'Battery replacement (labour)', price: 600, unit: 'visit' },
      { id: 's3', name: 'Full service (labour)', price: 1800, unit: 'visit' },
      { id: 's4', name: 'Roadside assistance', price: 500, unit: 'visit' },
    ],
    serviceArea: ['Kirkos', 'Bole', 'Lideta', 'Yeka', 'Arada'],
    baseLocation: subcityGeo('kirkos'),
    startingPrice: 500,
    priceUnit: 'visit',
    rating: 4.7, reviewCount: 92, jobsCompleted: 310, yearsExperience: 14,
    responseRatePct: 93, medianResponseMinutes: 12, completionRatePct: 97,
    verified: true, badges: ['Mobile Service', 'Fast Responder'],
    availability: availability([1, 2, 3, 4, 5, 6], '07:30', '19:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Technical & vocational certificate (Level 4)', type: 'certification', verified: true }],
    joinedAt: Date.now() - 420 * 86400000,
    online: true,
  },
  {
    uid: 'pro-meseret',
    displayName: 'Meseret Abebe',
    businessName: 'Meseret Traditional Tailoring',
        about: 'Master tailor from Shiro Meda — 20 years of habesha kemis, wedding outfits and tilet work. Bring your fabric or choose from mine; perfect fit guaranteed with two fittings.',
    categoryIds: ['tailoring'],
    serviceIds: ['alterations', 'traditional-wear', 'embroidery'],
    services: [
      { id: 's1', name: 'Alterations (from)', price: 150, unit: 'flat' },
      { id: 's2', name: 'Custom habesha kemis', price: 3500, unit: 'flat' },
      { id: 's3', name: 'Men\'s traditional outfit', price: 2800, unit: 'flat' },
      { id: 's4', name: 'Tilet embroidery work', price: 600, unit: 'flat' },
    ],
    serviceArea: ['Gullele', 'Arada', 'Kirkos', 'Yeka', 'Addis Ketema'],
    baseLocation: subcityGeo('gullele'),
    startingPrice: 150,
    priceUnit: 'flat',
    rating: 4.9, reviewCount: 134, jobsCompleted: 480, yearsExperience: 20,
    responseRatePct: 90, medianResponseMinutes: 35, completionRatePct: 99,
    verified: true, badges: ['Top Rated', 'Shiro Meda Craftswoman'],
    availability: availability([1, 2, 3, 4, 5, 6], '08:30', '18:30'),
    portfolio: [
      { id: 'p1', title: 'Wedding kemis with tilet', imageURL: 'https://images.unsplash.com/photo-1584239010545-e0f5a5f2a1d0?auto=format&fit=crop&w=600&q=70' },
    ],
    credentials: [{ id: 'c1', name: 'Tailoring & garment trade license', type: 'license', verified: true }],
    joinedAt: Date.now() - 520 * 86400000,
  },
  {
    uid: 'pro-dawitf',
    displayName: 'Dawit Fikru',
    businessName: 'SecureEth CCTV & Locks',
        about: 'CCTV, alarms, smart doorbells and locksmith work for homes and businesses. Phone viewing setup included, 1-year workmanship warranty, and 24/7 lockout response.',
    categoryIds: ['security', 'electrical'],
    serviceIds: ['cctv-install', 'locksmith', 'electrical-repair'],
    services: [
      { id: 's1', name: 'CCTV package (4 cameras installed)', price: 12000, unit: 'flat' },
      { id: 's2', name: 'Alarm system install', price: 6500, unit: 'flat' },
      { id: 's3', name: 'Lockout response', price: 400, unit: 'visit' },
      { id: 's4', name: 'Lock change (per lock)', price: 550, unit: 'visit' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Kirkos', 'Nifas Silk', 'Arada'],
    baseLocation: subcityGeo('bole'),
    startingPrice: 400,
    priceUnit: 'visit',
    rating: 4.8, reviewCount: 67, jobsCompleted: 150, yearsExperience: 9,
    responseRatePct: 95, medianResponseMinutes: 15, completionRatePct: 98,
    verified: true, badges: ['Warranty: 1 year', '24/7 Lockouts'],
    availability: availability([0, 1, 2, 3, 4, 5, 6], '07:00', '21:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Security systems installer license', type: 'license', verified: true }],
    joinedAt: Date.now() - 260 * 86400000,
    online: true,
  },
  {
    uid: 'pro-rahel',
    displayName: 'Rahel Tesfaye',
    businessName: 'Rahel Pet Care',
        about: 'Certified dog trainer and groomer. Dog walking, grooming, pet sitting while you travel, and basic training. Vaccinated pets welcome; photo updates sent every visit.',
    categoryIds: ['pets'],
    serviceIds: ['dog-walking', 'pet-grooming', 'pet-sitting'],
    services: [
      { id: 's1', name: 'Dog walking', price: 180, unit: 'hour' },
      { id: 's2', name: 'Grooming (wash + trim)', price: 500, unit: 'visit' },
      { id: 's3', name: 'Pet sitting (per day)', price: 350, unit: 'day' },
    ],
    serviceArea: ['Yeka', 'Bole', 'Kirkos'],
    baseLocation: subcityGeo('yeka'),
    startingPrice: 180,
    priceUnit: 'hour',
    rating: 4.9, reviewCount: 41, jobsCompleted: 95, yearsExperience: 4,
    responseRatePct: 97, medianResponseMinutes: 10, completionRatePct: 100,
    verified: true, badges: ['Rising Star', 'Photo Updates'],
    availability: availability([1, 2, 3, 4, 5, 6], '07:00', '19:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Animal handling certificate', type: 'certification', verified: true }],
    joinedAt: Date.now() - 140 * 86400000,
    online: true,
  },
  {
    uid: 'pro-tewodros',
    displayName: 'Tewodros Girma',
    businessName: 'TG Business Services',
        about: 'Accountant and certified translator (EN⇄AM) for NGOs and small businesses. Bookkeeping, tax filing, certified document translation, logo & print design through my partners.',
    categoryIds: ['business'],
    serviceIds: ['translation', 'bookkeeping', 'design-printing', 'cv-writing'],
    services: [
      { id: 's1', name: 'Translation (per page)', price: 300, unit: 'flat' },
      { id: 's2', name: 'Certified translation', price: 500, unit: 'flat' },
      { id: 's3', name: 'Monthly bookkeeping', price: 2500, unit: 'month' },
      { id: 's4', name: 'CV + cover letter package', price: 700, unit: 'flat' },
    ],
    serviceArea: ['Arada', 'Kirkos', 'Bole', 'Yeka', 'Lideta'],
    baseLocation: subcityGeo('arada'),
    startingPrice: 300,
    priceUnit: 'flat',
    rating: 4.8, reviewCount: 58, jobsCompleted: 210, yearsExperience: 8,
    responseRatePct: 92, medianResponseMinutes: 25, completionRatePct: 99,
    verified: true, badges: ['Certified Translator', 'NGO Experience'],
    availability: availability([1, 2, 3, 4, 5], '08:30', '18:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'BA Accounting + translation certification', type: 'certification', verified: true }],
    joinedAt: Date.now() - 310 * 86400000,
  },
  {
    uid: 'pro-selamawit',
    displayName: 'Selamawit Assefa',
    businessName: 'Selam Wellness Studio',
        about: 'Certified personal trainer and yoga instructor. At-home and outdoor sessions, beginner-friendly, with a simple nutrition plan included in every package.',
    categoryIds: ['wellness'],
    serviceIds: ['personal-training', 'yoga-pilates', 'nutrition'],
    services: [
      { id: 's1', name: 'Personal training', price: 400, unit: 'hour' },
      { id: 's2', name: 'Private yoga', price: 350, unit: 'hour' },
      { id: 's3', name: 'Nutrition plan', price: 800, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Kirkos', 'Arada'],
    baseLocation: subcityGeo('bole'),
    startingPrice: 350,
    priceUnit: 'hour',
    rating: 4.8, reviewCount: 46, jobsCompleted: 340, yearsExperience: 6,
    responseRatePct: 94, medianResponseMinutes: 20, completionRatePct: 98,
    verified: true, badges: ['Certified Trainer'],
    availability: availability([1, 2, 3, 4, 5, 6], '06:00', '20:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Fitness instructor certification (Level 3)', type: 'certification', verified: true }],
    joinedAt: Date.now() - 220 * 86400000,
    online: true,
  },
  {
    uid: 'pro-yohannes',
    displayName: 'Yohannes Bekele',
    businessName: 'EthioPest Control',
        about: 'Licensed pest control technician — cockroaches, bed bugs, rodents and termites. Safe chemicals, child & pet friendly, with a 3-month re-treatment guarantee.',
    categoryIds: ['pest-control'],
    serviceIds: ['pest-general', 'bed-bugs', 'rodent-removal'],
    services: [
      { id: 's1', name: 'Home treatment (up to 3 rooms)', price: 1200, unit: 'visit' },
      { id: 's2', name: 'Bed bug full treatment', price: 2500, unit: 'visit' },
      { id: 's3', name: 'Rodent control + proofing', price: 1000, unit: 'visit' },
    ],
    serviceArea: ['Nifas Silk', 'Kirkos', 'Bole', 'Lideta', 'Kolfe', 'Yeka'],
    baseLocation: subcityGeo('nifas-silk'),
    startingPrice: 1000,
    priceUnit: 'visit',
    rating: 4.6, reviewCount: 77, jobsCompleted: 260, yearsExperience: 7,
    responseRatePct: 89, medianResponseMinutes: 22, completionRatePct: 96,
    verified: true, badges: ['3-Month Guarantee', 'Pet Safe Options'],
    availability: availability([1, 2, 3, 4, 5, 6], '07:00', '18:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Pesticide application license', type: 'license', verified: true }],
    joinedAt: Date.now() - 280 * 86400000,
  },
  {
    uid: 'pro-genet',
    displayName: 'Genet Mengistu',
    businessName: 'Genet Driving Academy',
        about: 'Patient, calm driving instructor with dual-control cars. 1,200+ students taught; 92% pass rate at the Kality test. Manual and automatic lessons, plus test-day car rental.',
    categoryIds: ['driving'],
    serviceIds: ['driving-lessons', 'license-prep'],
    services: [
      { id: 's1', name: 'Driving lesson (per hour)', price: 700, unit: 'hour' },
      { id: 's2', name: '10-lesson package', price: 6500, unit: 'flat' },
      { id: 's3', name: 'Test prep + test-day car', price: 2500, unit: 'flat' },
    ],
    serviceArea: ['Bole', 'Yeka', 'Kirkos', 'Nifas Silk', 'Akaki'],
    baseLocation: subcityGeo('bole'),
    startingPrice: 700,
    priceUnit: 'hour',
    rating: 4.9, reviewCount: 112, jobsCompleted: 380, yearsExperience: 11,
    responseRatePct: 91, medianResponseMinutes: 30, completionRatePct: 97,
    verified: true, badges: ['92% Pass Rate', 'Dual-Control Cars'],
    availability: availability([1, 2, 3, 4, 5, 6], '06:30', '18:00'),
    portfolio: [],
    credentials: [{ id: 'c1', name: 'Driving instructor license (Grade A)', type: 'license', verified: true }],
    joinedAt: Date.now() - 390 * 86400000,
  },
];

export function demoProById(uid: string): ProfessionalProfile | undefined {
  return DEMO_PROFESSIONALS.find((p) => p.uid === uid);
}
