// Generated by FlutterFire CLI: flutterfire configure
// Replace with your Firebase project options.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFf70-t2hJuNMm0p3CjATGKCWGLosNW_k',
    appId: '1:700868166519:android:cba9bdb3c2bb9f6d9cd772',
    messagingSenderId: '700868166519',
    projectId: 'betegna-9bc61',
    storageBucket: 'betegna-9bc61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbq-syGYok27ae5ttJSF_cq3lgH14sj3o',
    appId: '1:700868166519:ios:e7020c3d6ccca2439cd772',
    messagingSenderId: '700868166519',
    projectId: 'betegna-9bc61',
    storageBucket: 'betegna-9bc61.firebasestorage.app',
    iosClientId: '700868166519-4uveg6bf4ul469ubuo4apnsorkaj5c9v.apps.googleusercontent.com',
    iosBundleId: 'com.betegna.betegna',
  );

}